function [rel_depth_1, rel_depth_2] = marge_rel_depth(output_component, input_size, output_size)

io_ratio = input_size ./ output_size;
rel_depth_1_split = reshape(1./output_component.row, [output_size(1), output_size(1), io_ratio(1), io_ratio(2)]);
rel_depth_2_split = reshape(output_component.col, [output_size(2), output_size(2), io_ratio(1), io_ratio(2)]);
rel_depth_1 = zeros(input_size(1), input_size(1));
rel_depth_2 = zeros(input_size(2), input_size(2));

for index_row_split = 1 : io_ratio(1)
    for index_col_split = 1 : io_ratio(2)
        rel_depth_1( ...
            (index_row_split-1)*output_size(1)+1:index_row_split*output_size(1), ...
            (index_col_split-1)*output_size(1)+1:index_col_split*output_size(1) ...
            ) ...
            = rel_depth_1_split(:,:,index_row_split,index_col_split);
        rel_depth_2( ...
            (index_row_split-1)*output_size(2)+1:index_row_split*output_size(2), ...
            (index_col_split-1)*output_size(2)+1:index_col_split*output_size(2) ...
            ) ...
            = rel_depth_2_split(:,:,index_row_split,index_col_split);
    end
end

rel_depth_1 = exp(log(rel_depth_1) - mean(log(rel_depth_1(:))));
rel_depth_2 = exp(log(rel_depth_2) - mean(log(rel_depth_2(:))));