function valid_range = valid_range_maker_v2(input_size, type)

if type == 1
    window = [...
        0 1 0;...
        1 1 1;...
        0 1 0];
elseif type == 2
    window = [...
        1 1 1;...
        1 1 1;...
        1 1 1];
elseif type == 4
    window = [...
        0 0 1 0 0;...
        0 1 1 1 0;...
        1 1 1 1 1;...
        0 1 1 1 0;...
        0 0 1 0 0];
elseif type == 5
    window = [...
        0 1 1 1 0;...
        1 1 1 1 1;...
        1 1 1 1 1;...
        1 1 1 1 1;...
        0 1 1 1 0];
elseif type == 8
    window = [...
        1 1 1 1 1;...
        1 1 1 1 1;...
        1 1 1 1 1;...
        1 1 1 1 1;...
        1 1 1 1 1];
end
    
distance = floor(sqrt(type)); 
row_size = input_size(1)^2;
col_size = input_size(2)^2;
rc_ratio = input_size(1)/input_size(2);

valid_range = zeros(input_size(1), input_size(1), input_size(2), input_size(2));

for index_row_col = 1 : input_size(1)
    for index_row_row = 1 : input_size(1)
        
        index_col_col = ceil(index_row_col/rc_ratio);
        index_col_row = ceil(index_row_row/rc_ratio);
        
        index_col_col_start = max(index_col_col-distance, 1);
        index_col_col_end = min(index_col_col+distance, input_size(2)); %index_col_col_start + 2*distance;
        index_col_row_start = max(index_col_row-distance, 1);
        index_col_row_end = min(index_col_row+distance, input_size(2)); %index_col_row_start + 2*distance;
        index_window_col_start = index_col_col_start - (index_col_col-distance);
        index_window_col_end = (index_col_col+distance) - index_col_col_end;
        index_window_row_start = index_col_row_start - (index_col_row-distance);
        index_window_row_end = (index_col_row+distance) - index_col_row_end;
        
        valid_range(index_row_row, index_row_col, index_col_row_start:index_col_row_end, index_col_col_start:index_col_col_end) ...
            = permute(window(1+index_window_row_start:end-index_window_row_end, 1+index_window_col_start:end-index_window_col_end), [3,4,1,2]);
    end
end

valid_range = reshape(valid_range, [row_size, col_size]);